### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by not-nef** [not-nef/onyx#42]

**Comment by Moosems** [comment]
I can do this for Mac and, with some guidance, set this up for windows 😁

**Comment by sumeshir26** [comment]
What if we make this a settings tab?

**Comment by im-coder-lg** [comment]
Well, anything I can do? I can't promise, but I think I could have some time with my PC. Even when my first exam for the year starts on Tuesday.

**Comment by not-nef** [comment]
> What if we make this a settings tab?

Nah i thing well put it in the settings dropdown.

**Comment by not-nef** [comment]
@Moosems feel free to add it! (I think you can find where it belongs in the code) But could you please please take a look at [this](https://github.com/not-nef/txt2/issues/15#issuecomment-1192796253) first? I can provide you instructions for the about page afterwards.
