### ISSUE TITLE
Window is too... big? 

### ISSUE THREAD

**Issue by sadjok** [not-nef/onyx#45]
Advance :
I think the window is too big and i found a nice size it is width : 1074 height : 580
Bug:
When you change the theme and it won't changed all window's tools theme

My program with the size : https://github.com/sadjok/CodeNoteBook

**Comment by not-nef** [comment]
The size of the window is set dynamically because some people have different window resolutions. (I have 1920x1080) So we can just change it in [this file](https://github.com/not-nef/txt2/blob/main/src/generatesize.py)

**Comment by sadjok** [comment]
Oh, okay.

**Comment by Moosems** [comment]
@not-nef I don't want to pester the idea but if we use a grid layout with a minimum size that scales up then it should fit all resolutions a bit better

**Comment by not-nef** [comment]
I guess, but as i said, im not gonna implement grid cuz its way too much work
