### ISSUE TITLE
Request: Update requirements.txt with most required modules with OS locks 

### ISSUE THREAD

**Issue by im-coder-lg** [not-nef/onyx#60]
In gist:
The title

Reason:
It is hard, as of now, to start developing on a barebones Onyx(previously Txt2) without module errors on Darwin and Tux(Darwin is the architecture name for Macs and Tux[ik it's not official but it seems better that way] as Linux). Since Onyx's primary devsystem is on Windows, it is a bit hard to just kickstart devwork on the other systems. Hence what I am asking is to test on any POSIX-COMPLIANT systems for modules and lock the ones needed only for Windows, plus include the modules previously marked as not installed on the pip directories.

How to achieve:
Simple. Head onto Gitpod or hit this link: https://gitpod.io/#https://github.com/not-nef/onyx and install all the modules. Then run main.py, expect an error, install the module+append the name to requirements.txt and keep repeating until all modules work and Python throws a nodisplay-ish error.

Or just give me a week's time and get the PR on Sunday. How's that sound?

Liberations:
From a lot of errors and failures on Darwin and Tux

Complications:
More logs to manage on the console(who cares?).

Finally:
Up to you @not-nef. I spoke my part. Now the ball is in your court.

**Comment by im-coder-lg** [comment]
And I powerbump on that.

**Comment by not-nef** [comment]
and i pass the ball back to you and let you do it :)

**Comment by im-coder-lg** [comment]
![oh yeah](https://tenor.com/oFN3osYbxtz.gif)

Chosen randomly, the Rajnikanth GIF seems good here.

**Comment by not-nef** [comment]
yeah i dont even know what you mean with locking modules.

**Comment by im-coder-lg** [comment]
<div class="tenor-gif-embed" data-postid="12178550570444919527" data-share-method="host" data-aspect-ratio="1.60714" data-width="100%"><a href="https://tenor.com/view/46-years-of-rajinism-rajini-rajinikanth-rajinism-narasimha-gif-12178550570444919527">46 Years Of Rajinism.Gif GIF</a>from <a href="https://tenor.com/search/46+years+of+rajinism-gifs">46 Years Of Rajinism GIFs</a></div> <script type="text/javascript" async src="https://tenor.com/embed.js"></script>

Let's gooooo

PS: that gif is the best, I am smart to choose that randomly.

**Comment by im-coder-lg** [comment]
![let's go](https://media.tenor.com/qQLnOBaAEucAAAAC/46-years-of-rajinism-rajini.gif)

Will implement by Saturday on my system, upload by Sunday bud.

PS: had to work hard to get tha gif here, it is the best rn

**Comment by im-coder-lg** [comment]
Lock the modules to Windows only with a few 'strings'. Look, I just talked JavaScript haha.

**Comment by not-nef** [comment]
btw what do you think of the new name?

**Comment by im-coder-lg** [comment]
Cooler than before, just update the icon, it looks like a blob. Maybe try making a better one vis GIMP.

**Comment by sumeshir26** [comment]
@im-coder-lg are you locing the moduleslike I did in TimerX's requirements.txt?

**Comment by sumeshir26** [comment]
@not-nef I like the new name a lot!

**Comment by HuyHung1408** [comment]
> btw what do you think of the new name?

I like the new icon and the new name tbh, although the icon does not relate to Onyx but I do like it tho :)

**Comment by not-nef** [comment]
> > btw what do you think of the new name?
> 
> 
> 
> I like the new icon and the new name tbh, although the icon does not relate to Onyx but I do like it tho :)

the icon as an onyx wdym

**Comment by HuyHung1408** [comment]
> > > btw what do you think of the new name?
> > 
> > 
> > I like the new icon and the new name tbh, although the icon does not relate to Onyx but I do like it tho :)
> 
> the icon is an onyx wdym

Never heard of an onyx before so... 🤣

**Comment by rdbende** [comment]
> It is hard, as of now, to start developing on a barebones Onyx(previously Txt2) without module errors on Darwin and Tux(Darwin is the architecture name for Macs and Tux[ik it's not official but it seems better that way] as Linux). 

@im-coder-lg FYI: Tux is the name of the penguin. Are you saying, that a cartoon penguin runs on my computer right now? 🐧🙃

**Comment by im-coder-lg** [comment]
> FYI: Tux is the name of the penguin. Are you saying, that there's a cartoon penguin running on my computer right now? 🐧🙃
from @rdbende 

Well, lil' Tux is the Linux mascot, won't it be cool if it was the arch name, like `tux-amd64`?
I want it to be the arch name too, so that it could be cool.

> are you locking the modules like I did in TimerX's requirements.txt?
from @sumeshir26 

Yeah sorta. I will verify it works too, then I will make my PR.

I will try uploading the PR by today. It is a Saturday for me, which means a half-day from the torture with the classmates at school. Honestly, you wouldn't want to know the atrocities they do. Once I am back, I will test and upload my edit here.

---

**Comment by im-coder-lg** [comment]
And sorry for the delay in sending that huge comment, I was sleeping( midnight IST).

**Comment by im-coder-lg** [comment]
There we are.

Some foreword, https://github.com/not-nef/onyx/commit/7e2a317fa875c15a09b0e39b23fdff636ee962f0 is signed and it speaks for itself.
