### ISSUE TITLE
Change the current codeview implementation with the real deal because the real one fixed the issue you solved for Onyx

### ISSUE THREAD

**Issue by Moosems** [not-nef/onyx#61]

**Comment by not-nef** [comment]
Wont do this because theres no way to remove the scrollbars without editing the code

**Comment by Moosems** [comment]
There is, I've done it

**Comment by Moosems** [comment]
It's not that hard

**Comment by not-nef** [comment]
but how?

**Comment by rdbende** [comment]
It's

```python
codeview_instance._hs.grid_remove()
codeview_instance._vs.grid_remove()
```
if you really want it. But what's your problem with the scrollbars? 🤔

**Comment by not-nef** [comment]
i only want to remove the horizontal one because i just dont think it looks that good

**Comment by rdbende** [comment]
Then it's `codeview_instance._hs.grid_remove()`
